# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='consumption',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
