# Generated by Django 2.2.15 on 2024-04-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='cousumption_value',
            field=models.IntegerField(verbose_name='消費'),
        ),
    ]
