# Generated by Django 2.2 on 2024-02-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_auto_20240217_1056'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consumption',
            constraint=models.UniqueConstraint(fields=('user_id', 'datetime'), name='unique_customer'),
        ),
        migrations.AddConstraint(
            model_name='consumptiondetails',
            constraint=models.UniqueConstraint(fields=('user_id', 'date'), name='unique_customer'),
        ),
        migrations.AlterModelTable(
            name='consumption',
            table='consumption_consumption',
        ),
        migrations.AlterModelTable(
            name='consumptiondetails',
            table='consumption_consumptiondetails',
        ),
    ]
