# Generated by Django 2.2.28 on 2024-02-03 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consumption", "0003_auto_20240203_1238"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tariff",
            old_name="name",
            new_name="plan",
        ),
    ]
