# Generated by Django 2.2.28 on 2024-02-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consumption", "0005_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consumption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("consumption", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="consumption.User",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="consumption",
            constraint=models.UniqueConstraint(
                fields=("user", "datetime"), name="user_datetime_unique"
            ),
        ),
    ]
