# Generated by Django 2.2.28 on 2024-02-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0006_auto_20240204_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='consumption',
            new_name='value',
        ),
    ]
