# Generated by Django 2.2.28 on 2024-02-11 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0007_auto_20240204_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
